### ISSUE TITLE
lets check your model for over fitting per this paper many models have over fitting 

### ISSUE THREAD

**Issue by Sandy4321** [farizrahman4u/RNN-EM#1]
new drop out for embeddings layer : conventional drop outs leads to overfititng
http://arxiv.org/abs/1512.05287
A Theoretically Grounded Application of Dropout in Recurrent Neural Networks

Yarin Ga

**Comment by haichengyi** [comment]
Traceback (most recent call last):
File "C:/Users//Downloads/rnn/main.py", line 38, in 
model.add(RNNEM(input_dim=10, output_dim=10, nb_slots=8, memory_size=40))
File "C:\Users\\Downloads\rnn\rnn_em.py", line 14, in init
super(RNNEM, self).init(**kwargs)
File "D:\ProgramData\Anaconda3\lib\site-packages\keras\legacy\layers.py", line 897, in init
super(Recurrent, self).init(**kwargs)
File "D:\ProgramData\Anaconda3\lib\site-packages\keras\engine\topology.py", line 292, in init
raise TypeError('Keyword argument not understood:', kwarg)
TypeError: ('Keyword argument not understood:', 'input_dim')
