### ISSUE TITLE
Code not working on latest Keras version

### ISSUE THREAD

**Issue by rahulsengupta** [farizrahman4u/RNN-EM#2]

**Comment by haichengyi** [comment]
Traceback (most recent call last):
  File "C:/Users/haicy/Downloads/rnn/main.py", line 38, in <module>
    model.add(RNNEM(input_dim=10, output_dim=10, nb_slots=8, memory_size=40))
  File "C:\Users\haicy\Downloads\rnn\rnn_em.py", line 14, in __init__
    super(RNNEM, self).__init__(**kwargs)
  File "D:\ProgramData\Anaconda3\lib\site-packages\keras\legacy\layers.py", line 897, in __init__
    super(Recurrent, self).__init__(**kwargs)
  File "D:\ProgramData\Anaconda3\lib\site-packages\keras\engine\topology.py", line 292, in __init__
    raise TypeError('Keyword argument not understood:', kwarg)
TypeError: ('Keyword argument not understood:', 'input_dim')
